name: trigger_axon


on:
  workflow_dispatch:
    inputs:
      GitUrlForAxon:
        description: 'Axon -git url'
        default: 'https://github.com/nervosnetwork/axon.git'
      GitBranchForAxon:
        description: 'axon  -git branch'
        default: 'main'
      StartAxon:
        description: 'start axon'
        default: 'true'

        
jobs:
  contract-tests:
    strategy:
      fail-fast: false
      matrix:
        net: ['testnet_v1']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"


      - name: Install dependencies
        run: yarn install

      # This is required separately from yarn test because it generates the typechain definitions
      - name: Compile
        run: yarn compile

      - name: Deploy Local Network of Axon
        run: |
          if [ ${{ github.event.inputs.StartAxon }} == "true" ];then
            git clone -b ${{ github.event.inputs.GitBranchForAxon }} ${{ github.event.inputs.GitUrlForAxon }}
            cd axon
            cargo build --package axon 
            cargo run --package axon --bin axon -- --config=./devtools/chain/config.toml --genesis=./devtools/chain/genesis_single_node.json > chain.log 2>&1 &
          fi
      - name: Run tests 0
        id: runtest
        run: |
          yarn test:prepare
          yarn test:runAll0
      - name: Run test 1
        if: success() || failure()
        run: |
          yarn test:runAll1
      - name: Run test 2
        if: success() || failure()
        run: |
          yarn test:runAll2
      - name: check axon status
        if: success() || failure()
        run: |
          curl http://localhost:8000 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params": [],"id":1}'
      - name: check axon log
        if: success() || failure()
        run: |
          tail -n 100 axon/chain.log
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: mochawesome-report/
